import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Loading from "../components/Loading";

import styles from "./indexStyles.module.scss";

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (loading === true) {
      setTimeout(() => {
        setLoading(false);
      }, 3000);
    }
  }, [loading]);

  return (
    <div className={loading === true ? styles.loadingMain : styles.main}>
      <Head>
        <title>Site da Georgina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loading loading={loading} />
      <main>
        <h1>Bem vindo ao site da georgina</h1>
      </main>

      <footer>Footer</footer>
    </div>
  );
}
