import { useState, useEffect } from "react";
import Head from "next/head";
import Loading from "../components/Loading";
import styles from "./indexStyles.module.scss";
import Menu from "../components/Menu";
import HeroSection from "../components/HeroSection";

const heroHeight = 700;

export default function Home() {
  const [loading, setLoading] = useState(true);


  useEffect(() => {
    if (loading === true) {
      setTimeout(() => {
        setLoading(false);
      }, 3000);
    }
  }, [loading]);

  return (
    <div className={loading === true ? styles.loadingMain : styles.main}>
      <Head>
        <title>Site da Georgina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loading loading={loading} />
      <main>
        <Menu scrollY={scrollY} showMenuOn={heroHeight / 3} />
        <HeroSection heroHeight={heroHeight} />
      </main>

      <footer>Footer</footer>
    </div>
  );
}
